#!/usr/bin/env python3
"""Two small content repairs for lessons generated by an older prompt.

1. JUNK POINTS — a knowledge point whose TITLE is a question, an exercise or a
   reading list ("思考题2：…", "推荐阅读：…", "本章小结：…"). These come from the
   slide's own exercise / summary / further-reading pages, which teach nothing: the
   page that teaches the content has its own point already. The generator no longer
   produces them; this removes the ones already stored. Points whose *explanation*
   merely mentions the word are left alone — only the title decides.

2. ODD DOLLAR SIGNS — a field with an odd number of `$` makes the renderer treat
   everything after the last one as mathematics, so the rest of the paragraph shows
   up as garbled italic formulas. Usually the `$` is a literal character in the slide
   text ("以 $ 和 & 两种转录本为例"). The repair walks the text left to right tracking
   paired math and escapes the single unmatched `$` (\\$), which leaves every real
   `$formula$` untouched.

Dry run by default; --apply writes. A database backup is taken before the first
write, and a rollback JSON records every change.

  python3 clean_point_junk.py --data-dir data-pku
  python3 clean_point_junk.py --data-dir data-pku --apply
  python3 clean_point_junk.py --data-dir data-pku --apply --only latex
"""
import argparse
import datetime as dt
import json
import os
import re
import sqlite3
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from db_backup import backup_database  # noqa: E402

JUNK_TITLE = re.compile(r"^\s*(思考题|练习题|习题|讨论题|作业|本章小结|小结|总结|复习题|推荐阅读|参考文献|思考与练习)")


def text_of(v):
    if isinstance(v, list):
        return "\n".join(str(x) for x in v)
    return v if isinstance(v, str) else ""


def balance_dollars(s):
    """Escape a `$` that cannot be mathematics. Returns (new, changed).

    Only the unambiguous case is repaired: a field containing exactly ONE `$`. That
    one is a literal character from the slide — a currency amount ("$772,500",
    "US$604 billion") or a placeholder in "以 $ 和 & 两种转录本" — and escaping it is
    always right, because an odd dollar count makes the renderer treat the rest of the
    paragraph as mathematics. A field with three or more `$` could be a real formula
    that lost its closer, and escaping the wrong one garbles the mathematics
    differently instead of fixing it; those are reported and left alone.
    """
    if s.count("$") - s.count("\\$") != 1:
        return s, False
    i = s.find("$")
    while i > 0 and s[i - 1] == "\\":
        i = s.find("$", i + 1)
    if i < 0:
        return s, False
    return s[:i] + "\\$" + s[i + 1:], True


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data-dir", required=True)
    ap.add_argument("--only", choices=["junk", "latex"], default=None)
    ap.add_argument("--apply", action="store_true")
    args = ap.parse_args()
    db_path = os.path.join(args.data_dir, "data.db")
    db = sqlite3.connect(db_path)
    rows = list(db.execute("SELECT id, data FROM records WHERE store='lessons'"))

    stamp = dt.datetime.now().strftime("%Y%m%d-%H%M%S")
    if args.apply:
        backup_database(db_path, os.path.join(args.data_dir, f"data.db.bak-cleanjunk-{stamp}"))

    rollback, changed_lessons = [], 0
    n_junk = n_latex = 0
    for lid, data in rows:
        lesson = json.loads(data)
        points = lesson.get("points") or []
        keep, removed, fixed = [], [], 0
        for p in points:
            title = (p.get("title") or "").strip()
            if args.only != "latex" and JUNK_TITLE.match(title):
                removed.append({"title": title, "slide": p.get("slide")})
                n_junk += 1
                continue
            if args.only != "junk":
                for field in ("explanation", "supplement", "mnemonic"):
                    original = text_of(p.get(field))
                    if not original:
                        continue
                    balanced, did = balance_dollars(original)
                    if did:
                        p[field] = balanced
                        fixed += 1
                        n_latex += 1
                for field in ("title",):
                    original = text_of(p.get(field))
                    if original:
                        balanced, did = balance_dollars(original)
                        if did:
                            p[field] = balanced
                            fixed += 1
                            n_latex += 1
            keep.append(p)
        if not removed and not fixed:
            continue
        changed_lessons += 1
        print(f"· {(lesson.get('title') or '?')[:40]}")
        for r in removed:
            print(f"    删除知识点：{r['title'][:56]}")
        if fixed:
            print(f"    修复 $ 不成对：{fixed} 处")
        rollback.append({"lessonId": lid, "title": lesson.get("title"),
                         "removed": removed, "pointsBefore": points})
        if args.apply:
            lesson["points"] = keep
            db.execute("UPDATE records SET data=? WHERE store='lessons' AND id=?",
                       (json.dumps(lesson, ensure_ascii=False), lid))

    print(f"\n{'已处理' if args.apply else '（试运行）将处理'} {changed_lessons} 门课："
          f"删除垃圾知识点 {n_junk} 条，修复 $ 不成对 {n_latex} 处")
    if not args.apply:
        print("加 --apply 才写入。")
        return 0
    db.commit()
    db.close()
    path = os.path.join(args.data_dir, f"point-junk-rollback-{stamp}.json")
    with open(path, "w", encoding="utf-8") as fh:
        json.dump({"createdAt": stamp, "lessons": rollback}, fh, ensure_ascii=False)
    print(f"回滚文件: {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
